#!/bin/sh
#
# ~/.config/bspwm/bspwmrc
# sushixnyan <sushixnyan@gmail.com> [2014]

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc rule -a Firefox desktop=^4
bspc rule -a Skype floating=on
bspc rule -a scratchpad floating=on sticky=on center=on

bspc config border_width	2
bspc config window_gap		2
bspc config split_ratio		0.50
bspc config borderless_monocle	true
bspc config gapless_monocle	true

bspc config right_padding	-2
bspc config left_padding	-2
bspc config bottom_padding	-2
bspc config top_padding		20

bspc control --subscribe > $PANEL_FIFO &
